version: '3.8'

services:
  redis:
    container_name: interstory-redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - interstory-network

volumes:
  redis_data:
    driver: local

networks:
  interstory-network:
    driver: bridge